name: 'Close inactive issues'
on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 1 * * *'

jobs:
  
  notify_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
          
      - name: Install dependencies
        run: |
          npm install @octokit/rest node-fetch
          
      - name: Notify on stale issues
        run: node .github/scripts/close_inactive/notify_stale_issues.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  close_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
          
      - name: Install dependencies
        run: |
          npm install @octokit/rest node-fetch
          
      - name: set stale issues
        run: node .github/scripts/close_inactive/close_stale_issues.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
