name: 'Close inactive issues'
on:
  #workflow_dispatch:
  schedule:
   - cron: '0 1 * * *'


jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.'
          stale-pr-message: 'This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to contact the Fil+ Gov team to re-open the application if it is still being processed. Thank you!'
          close-issue-message: 'This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to contact the Fil+ Gov team to re-open the application if it is still being processed. Thank you!'
          days-before-stale: 10
          days-before-close: 4
          days-before-pr-close: -1
          operations-per-run: 1000
          ascending: true
