name: 'Close inactive issues'
#on:
 #schedule:
  #  - cron: '0 1 * * *'
on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: 'This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to re-open if this is relevant, or start a new application for DataCap anytime. Thank you!'
          stale-pr-message: 'This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to re-open if this is relevant, or start a new application for DataCap anytime. Thank you!'
          close-issue-message: ''
          days-before-stale: 14
          days-before-close: 0
          days-before-pr-close: -1
